/*
package ошибка;

import java.io.FileNotFoundException;
import java.io.IOException;
public class Main {
    public static void main(String[] args) {
        try {
            foo();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (FileNotFoundException e) { //java: exception java.io.FileNotFoundException has already been caught
            e.printStackTrace(); //java: исключение java.io.FileNotFoundException уже было перехвачено
        }
    }
    public static void foo() throws IOException, FileNotFoundException {}
    }*/
